In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace = True)

In [6]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

now train test split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2)

scaling

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[ 0.62626887, -0.75698135,  0.63882427, ...,  0.2131461 ,
         0.47852217,  0.34822642],
       [-0.00430524, -0.85192082, -0.07264771, ..., -0.45562731,
        -1.26156015, -0.91780977],
       [ 1.53546875,  1.65123943,  1.55850078, ...,  1.04482984,
         1.36652877,  1.62551627],
       ...,
       [ 1.03687527, -0.99317223,  1.00924953, ...,  0.53242544,
        -0.200743  , -0.23752632],
       [ 2.70862989,  0.62543   ,  2.58887911, ...,  1.91856501,
         1.22451616,  0.47595541],
       [ 0.2420586 , -0.55552442,  0.15301366, ..., -0.49378509,
        -0.59598294, -0.85197589]])

In [10]:
y_train

375    B
439    B
33     M
280    M
523    B
      ..
364    B
456    B
29     M
164    M
434    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0])

Numpy arrays to PyTorch tensors

In [13]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [16]:
y_train_tensor.shape

torch.Size([455])

In [19]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [20]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

In [22]:
train_dataset[10]

(tensor([-1.0895, -0.6921, -1.1064, -0.9371, -0.1023, -1.0215, -1.0008, -1.1166,
          0.3106, -0.0890, -0.6804, -0.4405, -0.7206, -0.5680,  0.0272, -1.0496,
         -0.8826, -1.0214, -0.6019, -0.4589, -1.0389, -0.6326, -1.0774, -0.8609,
         -0.1343, -1.0692, -1.0991, -1.3644, -0.3291, -0.5301]),
 tensor(0.))

In [23]:
train_loader = DataLoader(train_dataset, batch_size = 32, shuffle = True)
test_loader = DataLoader(test_dataset, batch_size = 32, shuffle = True)

Defining the model

In [30]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.Sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.Sigmoid(out)

    return out

Important Parameters

In [31]:
learning_rate = 0.1
epochs = 25

In [32]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loss function
loss_function = nn.BCELoss()

Training Pipeline

In [33]:
# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    #loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1, 1))

    #clear gradients
    optimizer.zero_grad()

    #backward pass
    loss.backward()

    #parameters update
    optimizer.step()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.2964939773082733
Epoch: 2, Loss: 0.22529833018779755
Epoch: 3, Loss: 0.03777598962187767
Epoch: 4, Loss: 0.0604703426361084
Epoch: 5, Loss: 0.18355692923069
Epoch: 6, Loss: 0.11931735277175903
Epoch: 7, Loss: 0.09736113995313644
Epoch: 8, Loss: 0.1031959056854248
Epoch: 9, Loss: 0.08431309461593628
Epoch: 10, Loss: 0.09776409715414047
Epoch: 11, Loss: 0.2013213187456131
Epoch: 12, Loss: 0.1385791003704071
Epoch: 13, Loss: 0.01173052005469799
Epoch: 14, Loss: 0.014711176976561546
Epoch: 15, Loss: 0.03511336073279381
Epoch: 16, Loss: 0.08388318866491318
Epoch: 17, Loss: 0.020838875323534012
Epoch: 18, Loss: 0.0022118561901152134
Epoch: 19, Loss: 0.04358040168881416
Epoch: 20, Loss: 0.09562672674655914
Epoch: 21, Loss: 0.058169782161712646
Epoch: 22, Loss: 0.3026888966560364
Epoch: 23, Loss: 0.08501576632261276
Epoch: 24, Loss: 0.04313741251826286
Epoch: 25, Loss: 0.010447180829942226

Evaluation

In [35]:
# Model evaluation using test_loader
model.eval()
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    # forward pass
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float() # Convert probabilities to binary predictions

    # calculates accuracy for the current batch
    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accuracy: {overall_accuracy:.4f}")

Accuracy: 0.9644